### ISSUE TITLE
Trouble creating register in French

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#100]
When populating items in the register, the French version is having trouble when I put in the Gestité component name (from the [Prenatal Number of pregnancies](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=41&start=&action=view) screen). 

See [link](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=30&start=&action=edit&id=155)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
@whppawan Issue still persists (French language only. Ok in English and Swahili).
