### ISSUE TITLE
Register sorting is not correct

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#107]
On the register, the items should be sorted by the date the patient was initially entered into the app (it doesn't matter if the patient info was edited at a later date). However, see the bottom 3 entries on this screenshot. They are not properly sorted. I believe the mismatched sorting happens after editing a patient. 

![screenshot_2017-03-31-10-02-38](https://cloud.githubusercontent.com/assets/9537700/24560863/481f2242-15f9-11e7-98de-01a3e951be0e.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Wrong sorting still happening after editing a patient. Here's how to recreate: 
1. Go to register view
2. Click on a patient to go to the patient summary screen (click a patient in the middle of the register, note the position in the register)
3. On the patient summary screen, click edit
4. Edit the patient's first name, then go back to the register view
5. The patient's position in the register has changed.
