### ISSUE TITLE
Prod doesn't match dev admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#139]
Did you move screens over from dev to prod? In prod, the Code PTME screen shows up after logging in. In prod, its sequence number is 0. In dev, its sequence number is 11.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Still doesn't match. The Prenatal Appt screen in prod is saving the OK value, whereas the value in Dev is not. I'm manually changing this so that LTFHC won't have issues, but I'm very surprised this wasn't checked.
