### ISSUE TITLE
Too many reports in admin backend

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#190]
I checked the prod site and 2191 reports show up. If I filter to Kalemie, Kataki, Jan 2018, I get 88 reports. Can you check why so many reports are showing up in the system?

**Comment by whppawan** [comment]
Done.
Earlier Filter was not working properly, Now all the filter has been applied.

**Comment by space-ravi** [comment]
Something with the filter is still not working correctly. See the attached screenshot as an example. There are many clinique d'Etat options. When I select any of them and click filter, nothing shows up in the report list.  

<img width="1433" alt="screen shot 2018-02-12 at 7 06 40 pm" src="https://user-images.githubusercontent.com/9537700/36131697-edee2d84-1027-11e8-980d-891dabf59dca.png">

**Comment by whppawan** [comment]
This occurs due to free text entry. There are some hidden characters saved which makes the text different.
We have fixed for some of them but still need to work.

**Comment by space-ravi** [comment]
Ok, I'll reassign to you. Please reassign to me when you have completed fixing the issue.
