### ISSUE TITLE
Text edit needed in admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#216]
When adding a health area, the "Name" field says "Enter Health Zone". It should say "Enter Health Area". 

<img width="1530" alt="screen shot 2018-04-07 at 3 12 50 pm" src="https://user-images.githubusercontent.com/9537700/38460811-7c77c83a-3a76-11e8-83ff-a913774ee719.png">

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Still showing up the same for me: 
http://whpeportal.org/ltfhcdynamic/admin/index.php?page=health_area&parrent_page=location&action=add

**Comment by whppawan** [comment]
Done
