### ISSUE TITLE
Admin shows wrong image

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#26]
When replacing an image in the admin, the admin does not show the updated image. 

For example, I deleted the image [here](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=20&start=&action=edit&id=50) and replaced it with a different one. After replacing it, the image does not show up in the admin. After leaving the screen and coming back to it, the old image is back. 

However, in the app, the updated image appears.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Issue still persists. 

For the example, I am trying to replace the left arrow with this image (right arrow, which is white, so doesn't show up here!): 
![arrow-right-thick](https://cloud.githubusercontent.com/assets/9537700/22619375/4938d384-eaa8-11e6-81b2-79d1428ebd89.png)

Gif shows that the admin continues to see the left arrow after replacing the image: 
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/9537700/22619378/4cad709c-eaa8-11e6-91fe-09bd54b0208d.gif)

**Comment by space-ravi** [comment]
Not working still. I created a new screen and the images are not showing up in the admin (or on the screen in the app). 

See: http://whpeportal.org/ltfhcdynamic/admin/index.php?page=component&search_screen_id=86&start=&action=edit&id=546

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Same issue still persists. I am trying to change the backward arrow for the patient summary screen. After deleting the image, uploading a new image, and clicking submit, the old image appears.

**Comment by space-ravi** [comment]
Hmm, seems I have to clear my cache and then it works...
