### ISSUE TITLE
Rows in Maternity register are not aligned

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#274]
Version: "LTFHC 10th Oct.apk"
Data uploaded to server, user rprakash, Oct 11.

See screenshot. 

![Screenshot_2019-10-11-09-04-35](https://user-images.githubusercontent.com/9537700/66668207-8878f500-ec09-11e9-854b-c2e2fdec6eac.png)

**Comment by vishal7626** [comment]
@space-ravi this issue was fixed in last build of 18th Oct.

**Comment by whpVishal** [comment]
@space-ravi this issue is fixed in last build shared on 18th Oct

**Comment by space-ravi** [comment]
Using Oct18 APK, still see this issue. Uploaded data for user rprakash on 07-Nov-2019. 
![Screenshot_2019-11-07-12-03-49](https://user-images.githubusercontent.com/9537700/68423382-e50ef780-0156-11ea-869b-a1c2f241d22a.png)

**Comment by whpVishal** [comment]
@space-ravi I have checked for user 'rprakash' and it is aligned, there might be some data issue. please share the tablet db.

![Screenshot_20191108-092256](https://user-images.githubusercontent.com/46335366/68461313-e95b1380-022f-11ea-8d37-e46d087bd1a6.png)

**Comment by space-ravi** [comment]
When you say to share the tablet db, you mean to upload my data? I already did that (that was my note in the previous comment: Uploaded data for user rprakash on 07-Nov-2019.)

**Comment by whpVishal** [comment]
i was asking to attach the ltfhc.db file in mail and share it with me.

**Comment by space-ravi** [comment]
My understanding is that when I press "upload" it uploads the ltfhc.db file somewhere that you can retrieve it. If you cannot, then the upload button is not working.

**Comment by whpVishal** [comment]
@space-ravi upload button is working. i have checked over sep,oct and nov data. They are visible and aligned properly.

**Comment by space-ravi** [comment]
Still not working properly for me. Are you testing this on a Nexus 7 tablet? This is on version LTFHC Demo 13th Jan.apk.

Same issue is also happening on CPoN register.
![Screenshot_2020-02-14-10-39-23](https://user-images.githubusercontent.com/9537700/74558247-c7e88280-4f16-11ea-82c1-df608fe533f5.png)

![Screenshot_2020-02-14-10-33-31](https://user-images.githubusercontent.com/9537700/74558257-cdde6380-4f16-11ea-9316-cf4d066267de.png)

**Comment by whpVishal** [comment]
Hello @space-ravi ,
     I was looking in to this and found that the title header row and the value row have different number of columns.
     Either one of the header title have extra column or the values is missing one column.

Pleas check which one is missing and update the screen from backend.

**Comment by space-ravi** [comment]
Hi Vishal, I triple checked and saw that I had 32 components in the header and 32 components for values. I am also saving each of the components. If you count a different number, let me know what number of components you are seeing. Issue still persists.

**Comment by space-ravi** [comment]
Update: I think there is something fundamentally wrong. I am also experiencing this issue off and on with the Observation register. Which means I am seeing this on Maternity, CPoN, and Observation. I imagine if I check others, I will see this issue on others as well.

**Comment by space-ravi** [comment]
Note that 18Logic team cannot replicate this. Maybe this is related to the version of the OS? Or maybe related to empty data in a cell? Kamal to send APK and consider putting a null value if blank.

**Comment by whpVishal** [comment]
The width issue is resolved in new build. i will be sharing it in a while
