### ISSUE TITLE
OBGYN Report translation issues (French)

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#341]
In the OBGYN Report, French language, please fix the following:

"10.2 Types of Interventions" should be "10.2 Types d'interventions"
"10.3 Delivery Complications from the mother" should be "10.3 Complications accouchement chez la mère"

Under 10.3, please capitalize the items: 
"déchirure du col" should be "Déchirure du col"
"déchirure du périné" should be "Déchirure du périné"

**Comment by whpVishal** [comment]
This issue is fixed in new build i shared today.

**Comment by space-ravi** [comment]
Looks like you missed the latter part of the request: 
Under 10.3, please capitalize the items:
"déchirure du col" should be "Déchirure du col"
"déchirure du périné" should be "Déchirure du périné"

**Comment by whpVishal** [comment]
Issue Resolved in latest Build
