### ISSUE TITLE
Fields are missing when user goes back screens

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#91]
For example: If I enter patient given name, then press OK, then go BACK to the patient given name screen, the patient's name is not written there anymore.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
@whppawan still not working. Here is what I did: 
- Entered patient given name
- Entered patient family name
- On the "Patient's file number" screen, press the back button
- The patient family name is blank
